export const ROUTES = Object.freeze({
  home: "/",
  tours: "/tours",
  activities: "/activities",
  destinations: "/destinations",
  deals: "/deals",
  travelGuide: "/travel-guide",
  about: "/about",
  contact: "/contact",
  login: "/auth/login",
  signup: "/auth/signup",
  bookings: "/dashboards/bookings",
  profile: "/dashboards/profile",
  wishlist: "/dashboards/wishlist",
});
