import allImages from "@/components/helper/imageProvider";

// TODO(api): Activity pricing, review totals, and schedules below are mock catalog data pending API integration.
// TODO(content): Editorial review of schedules, inclusions, and meeting locations.

const { popularThings, trendingDestinations } = allImages;

export const experiences = [
  {
    id: "city-tours",
    slug: "paris-old-town-stories",
    title: "Old town stories & Latin Quarter highlights",
    description:
      "Wander past medieval bookstalls along the Seine, explore Roman bath ruins, and uncover Bohemian philosopher haunts with a native Parisian historian.",
    location: "Paris, France",
    destination: "Paris",
    country: "France",
    category: "Sightseeing",
    image: popularThings[0].image,
    images: [popularThings[0].image, trendingDestinations[0].image],
    duration: "3 hours",
    durationLabel: "3 hours",
    durationHours: 3,
    timeOfDay: "morning",
    group: "Small group",
    groupType: "Small group",
    groupSizeMax: 10,
    languages: ["English", "French"],
    price: 42.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.8,
    reviews: 184,
    features: ["freeCancellation", "localGuide", "mobileTicket", "instantConfirmation"],
    highlights: [
      "Latin Quarter hidden medieval alleys & Roman amphitheater ruins",
      "Shakespeare and Company historic bookstore exterior & folklore",
      "Sainte-Chapelle square architecture & Seine bridge viewpoints",
      "Artisan warm croissant & espresso stop at a local patisserie",
    ],
    included: [
      "Licensed English-speaking local historian guide",
      "Boutique cafe tasting (pastry and coffee/tea)",
      "Headsets for clear audio in quiet churches",
    ],
    excluded: ["Entry to paid monuments (optional on your own)", "Gratuities"],
    meetingPoint: "Saint-Michel Fountain, Place Saint-Michel, 75005 Paris",
    cancellationPolicy: "Free cancellation up to 24 hours before experience start for a full refund.",
    schedule: ["09:30 AM", "02:00 PM"],
    whatToBring: "Comfortable flat walking shoes, camera, light umbrella.",
    featured: true,
    popular: true,
  },
  {
    id: "culture-cappadocia",
    slug: "cappadocia-valleys-local-culture",
    title: "Cappadocia valleys & cave village culture",
    description:
      "Hike through the otherworldly volcanic formations of Pigeon and Rose Valleys, inspect 1,000-year-old rock-cut dove cotes, and enjoy homemade Anatolian tea inside a cave home.",
    location: "Cappadocia, Turkey",
    destination: "Cappadocia",
    country: "Turkey",
    category: "Culture",
    image: popularThings[1].image,
    images: [popularThings[1].image, trendingDestinations[7].image],
    duration: "5 hours",
    durationLabel: "5 hours",
    durationHours: 5,
    timeOfDay: "afternoon",
    group: "Small group",
    groupType: "Small group",
    groupSizeMax: 8,
    languages: ["English", "Turkish"],
    price: 68.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.9,
    reviews: 214,
    features: ["hotelPickup", "instantConfirmation", "localGuide", "freeCancellation"],
    highlights: [
      "Scenic walking route through Rose and Red Valley formations",
      "Traditional pottery masterclass in riverside Avanos workshop",
      "Family-run cave dwelling visit with fresh herbal tea & local honey",
      "Panoramic Uchisar rock fortress photo viewpoint",
    ],
    included: [
      "Roundtrip hotel pickup and drop-off in Goreme/Uchisar",
      "Professional certified Anatolian trekking guide",
      "Traditional pottery workshop demonstration and clay trial",
      "Tea, fruit, and mineral water refreshments",
    ],
    excluded: ["Souvenir pottery purchases", "Driver gratuities"],
    meetingPoint: "Hotel pickup included across Goreme, Uchisar, and Urgup",
    cancellationPolicy: "Free cancellation up to 48 hours before start.",
    schedule: ["01:30 PM"],
    whatToBring: "Sturdy trail sneakers or hiking shoes, sunglasses, sun hat.",
    featured: true,
    popular: true,
  },
  {
    id: "phuket-cruise",
    slug: "phuket-island-hopping-sea-caves",
    title: "Island hopping & turquoise sea cave exploration",
    description:
      "Speed across the emerald Andaman waters to Phang Nga Bay. Paddle inside hidden sea caves, swim off secluded sands, and marvel at soaring limestone monoliths.",
    location: "Phuket, Thailand",
    destination: "Phuket",
    country: "Thailand",
    category: "Water",
    image: popularThings[2].image,
    images: [popularThings[2].image, trendingDestinations[5].image],
    duration: "Full day",
    durationLabel: "Full day (7 hours)",
    durationHours: 7,
    timeOfDay: "full-day",
    group: "Shared boat",
    groupType: "Shared boat",
    groupSizeMax: 18,
    languages: ["English", "Thai"],
    price: 76.0,
    // TODO(compliance): confirm the original price was genuinely charged before launch, per applicable consumer-protection rules
    // TODO(api): Sync marine reserve seasonal promo and sea canoe operator contracts
    originalPrice: 95.0,
    validUntil: "2026-12-10",
    dealLabel: "Marine reserve deal",
    terms: ["National marine park permit included", "Free cancellation up to 24h before start"],
    currency: "USD",
    rating: 4.7,
    reviews: 156,
    features: ["freeCancellation", "mobileTicket", "hotelPickup", "instantConfirmation"],
    highlights: [
      "Phang Nga Bay tidal sea cave paddling with experienced steersman",
      "Snorkeling stops over shallow fringing reefs with clownfish",
      "Fresh Thai buffet lunch served at floating Koh Panyee village",
      "Beach relaxation time on quiet Naka Island",
    ],
    included: [
      "Hotel transfers across major Phuket beach resorts",
      "Buffet lunch on floating stilt island, seasonal fruits, and drinking water",
      "Inflatable sea canoe equipment with local paddler",
      "National marine park conservation entrance fees",
    ],
    excluded: ["Alcoholic beverages", "Underwater camera hire"],
    meetingPoint: "Ao Po Grand Marina, Pa Klok, Phuket (or hotel pickup)",
    cancellationPolicy: "Free cancellation up to 24 hours before departure.",
    schedule: ["08:00 AM"],
    whatToBring: "Swimwear, towel, waterproof phone pouch, reef-safe sunscreen.",
    featured: false,
    popular: true,
  },
  {
    id: "london-walk",
    slug: "london-royal-landmarks-secret-alleys",
    title: "Royal landmarks & hidden historic London",
    description:
      "Witness the Changing of the Guard, explore quiet gas-lit Victorian courtyards, and discover where secret societies and literary icons gathered away from tourist crowds.",
    location: "London, UK",
    destination: "London",
    country: "UK",
    category: "History",
    image: popularThings[3].image,
    images: [popularThings[3].image, trendingDestinations[10].image],
    duration: "3.5 hours",
    durationLabel: "3.5 hours",
    durationHours: 3.5,
    timeOfDay: "morning",
    group: "Walking tour",
    groupType: "Walking tour",
    groupSizeMax: 12,
    languages: ["English"],
    price: 39.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.8,
    reviews: 129,
    features: ["localGuide", "mobileTicket", "freeCancellation"],
    highlights: [
      "Clear view of the Changing of the Guard ceremony at St. James's Palace",
      "Hidden gas-lit alleyways of Covent Garden and Seven Dials",
      "The oldest operational tea merchant in London with tasting sample",
      "Historic Charles Dickens and Oscar Wilde tavern stories",
    ],
    included: [
      "Blue Badge accredited London heritage guide",
      "Specialty tea sample at centuries-old merchant shop",
      "Curated digital map of recommended historic pubs",
    ],
    excluded: ["Underground tube fares", "Food and drinks"],
    meetingPoint: "Trafalgar Square, on the steps beneath Nelson's Column",
    cancellationPolicy: "Free cancellation up to 24 hours before tour start for a full refund.",
    schedule: ["10:00 AM", "02:30 PM"],
    whatToBring: "Comfortable walking shoes, weather-appropriate jacket or umbrella.",
    featured: false,
    popular: true,
  },
  {
    id: "dubai-desert",
    slug: "dubai-desert-sunset-dinner-stars",
    title: "Desert sunset, dune safari & Bedouin dinner",
    description:
      "Leave the gleaming glass towers of Dubai behind. Ride in a 4x4 across red dunes, sandboard down steep crests, and dine beneath the Arabian desert stars at a traditional Bedouin camp.",
    location: "Dubai, UAE",
    destination: "Dubai",
    country: "UAE",
    category: "Adventure",
    image: popularThings[4].image,
    images: [popularThings[4].image, trendingDestinations[8].image],
    duration: "6 hours",
    durationLabel: "6 hours",
    durationHours: 6,
    timeOfDay: "evening",
    group: "Small group",
    groupType: "Small group",
    groupSizeMax: 6,
    languages: ["English", "Arabic"],
    price: 84.0,
    // TODO(compliance): confirm the original price was genuinely charged before launch, per applicable consumer-protection rules
    // TODO(api): Sync desert sunset promotional pricing with UAE safari operator allotments
    originalPrice: 105.0,
    validUntil: "2026-11-20",
    dealLabel: "Sunset promo",
    terms: ["Applies to afternoon safari slots", "Full Bedouin dune dinner included"],
    currency: "USD",
    rating: 4.9,
    reviews: 302,
    features: ["hotelPickup", "freeCancellation", "instantConfirmation", "localGuide"],
    highlights: [
      "4x4 red dune bashing in Lahbab desert with licensed safari pilot",
      "Sandboarding down glowing crimson dunes at golden hour",
      "Sunset camel caravan walk for photography",
      "Authentic grilled barbecue buffet dinner with Tanoura and fire performances",
    ],
    included: [
      "4x4 hotel pickup and drop-off anywhere in Dubai",
      "Unlimited chilled water, soft drinks, Arabic coffee (Gahwa) and dates",
      "Full BBQ dinner with vegetarian and meat options",
      "Henna painting demonstration and sandboard equipment",
    ],
    excluded: ["Quad bike / buggy rental (optional upgrade)", "Alcoholic beverages"],
    meetingPoint: "Complimentary hotel pickup from any Dubai hotel or residence",
    cancellationPolicy: "Free cancellation up to 24 hours before departure.",
    schedule: ["03:00 PM"],
    whatToBring: "Loose breathable clothes, sunglasses, flip-flops or slip-on sandals for sand.",
    featured: true,
    popular: true,
  },
  {
    id: "santorini-food",
    slug: "santorini-sunset-food-wine-walk",
    title: "Sunset culinary walk & volcanic wine tasting",
    description:
      "Stroll the clifftop rim of the caldera as dusk settles. Taste traditional tomato fritters, fresh Cycladic cheeses, fava puree, and crisp Assyrtiko volcanic wines in family-run tavernas.",
    location: "Santorini, Greece",
    destination: "Santorini",
    country: "Greece",
    category: "Food",
    image: popularThings[5].image,
    images: [popularThings[5].image, trendingDestinations[15].image],
    duration: "3 hours",
    durationLabel: "3 hours",
    durationHours: 3,
    timeOfDay: "evening",
    group: "Small group",
    groupType: "Small group",
    groupSizeMax: 10,
    languages: ["English", "Greek"],
    price: 55.0,
    // TODO(compliance): confirm the original price was genuinely charged before launch, per applicable consumer-protection rules
    // TODO(api): Sync caldera culinary tasting special with Santorini partner tavernas
    originalPrice: 70.0,
    validUntil: "2026-10-31",
    dealLabel: "Sunset tasting offer",
    terms: ["Valid for autumn season tastings", "Includes 4 volcanic wine pairings"],
    currency: "USD",
    rating: 4.8,
    reviews: 98,
    features: ["localGuide", "mobileTicket", "instantConfirmation", "freeCancellation"],
    highlights: [
      "Sunset viewpoints overlooking the caldera and volcanic rim",
      "Tasting of 4 certified PDO Santorini volcanic wines",
      "Authentic meze feast featuring tomato keftedes and grilled octopus",
      "Intimate backstreet tavernas away from crowded tourist strips",
    ],
    included: [
      "Local Greek food & wine specialist escort",
      "Generous food tastings equivalent to a full dinner",
      "4 glasses of local volcanic wine paired with dishes",
    ],
    excluded: ["Hotel transfers", "Extra bottles of wine for takeaway"],
    meetingPoint: "Main Square outside Orthodox Metropolitan Cathedral, Fira",
    cancellationPolicy: "Free cancellation up to 48 hours before tour start for a full refund.",
    schedule: ["05:30 PM"],
    whatToBring: "Comfortable flat walking shoes for stone steps, camera.",
    featured: false,
    popular: true,
  },
  {
    id: "barcelona-art",
    slug: "barcelona-gaudi-gothic-quarter-art",
    title: "Gaudí architecture & Gothic Quarter walking tour",
    description:
      "Discover the flamboyant modernisme palaces of Antoni Gaudí alongside Roman and medieval secrets. Admire Casa Batlló's dragon roof and explore the hidden plazas of the Gothic Quarter.",
    location: "Barcelona, Spain",
    destination: "Barcelona",
    country: "Spain",
    category: "Culture",
    image: popularThings[6].image,
    images: [popularThings[6].image, trendingDestinations[9].image],
    duration: "4 hours",
    durationLabel: "4 hours",
    durationHours: 4,
    timeOfDay: "morning",
    group: "Walking tour",
    groupType: "Walking tour",
    groupSizeMax: 12,
    languages: ["English", "Spanish"],
    price: 48.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.7,
    reviews: 143,
    features: ["instantConfirmation", "localGuide", "mobileTicket", "freeCancellation"],
    highlights: [
      "Detailed exterior architectural commentary on Casa Batlló & Casa Milà",
      "Plaça del Rei medieval royal palace square and Roman walls",
      "Barcelona Cathedral cloister with resident white geese",
      "Traditional churros and thick dipping chocolate break in a 19th-century granja",
    ],
    included: [
      "Accredited professional art history guide",
      "Churros con chocolate morning tasting",
      "Headsets for clear narration throughout the walk",
    ],
    excluded: ["Interior tickets to Casa Batlló or Sagrada Família"],
    meetingPoint: "Plaça de Catalunya, in front of the Zurich Cafe terrace, Barcelona",
    cancellationPolicy: "Free cancellation up to 24 hours before departure.",
    schedule: ["09:30 AM", "02:30 PM"],
    whatToBring: "Comfortable walking shoes, water bottle, sun protection.",
    featured: false,
    popular: true,
  },
  {
    id: "maldives-snorkel",
    slug: "maldives-coral-reef-snorkel-safari",
    title: "Coral gardens & sea turtle marine safari",
    description:
      "Cruise to outer atoll reefs to swim alongside peaceful green sea turtles, colorful parrotfish, and gentle reef sharks under the supervision of a certified marine biologist.",
    location: "Maldives",
    destination: "Maldives",
    country: "Maldives",
    category: "Nature",
    image: popularThings[7].image,
    images: [popularThings[7].image, trendingDestinations[14].image],
    duration: "Half day",
    durationLabel: "Half day (4 hours)",
    durationHours: 4,
    timeOfDay: "morning",
    group: "Small group",
    groupType: "Small group",
    groupSizeMax: 8,
    languages: ["English"],
    price: 92.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.9,
    reviews: 176,
    features: ["freeCancellation", "mobileTicket", "instantConfirmation"],
    highlights: [
      "Two guided snorkeling sessions at protected marine biodiversity reserves",
      "High probability turtle and eagle ray encounters",
      "Marine biologist briefing on coral restoration initiatives",
      "Fresh tropical fruit and coconut water on board the traditional dhoni boat",
    ],
    included: [
      "Traditional motorized dhoni boat charter",
      "High-grade silicone mask, snorkel, fins, and life jackets",
      "Marine biologist guide in the water with guests",
      "GoPro underwater photography shared after the tour",
    ],
    excluded: ["Wetsuit rental (warm water rarely requires one)"],
    meetingPoint: "Main Jetty, Malé / Hulhumalé Harbor or resort jetty",
    cancellationPolicy: "Free cancellation up to 48 hours before tour start for a full refund.",
    schedule: ["08:30 AM", "01:30 PM"],
    whatToBring: "Swimwear, reef-safe sunscreen, dry bag, towel.",
    featured: true,
    popular: true,
  },
  {
    id: "bali-waterfall-safari",
    slug: "bali-hidden-waterfalls-jungle-trek",
    title: "Hidden jungle waterfalls & sacred springs trek",
    description:
      "Hike beneath tropical canopy ferns to swim in secluded tiered waterfalls in northern Bali, visit lush cacao plantations, and receive a holy water blessing at a tranquil jungle shrine.",
    location: "Bali, Indonesia",
    destination: "Bali",
    country: "Indonesia",
    category: "Nature",
    image: trendingDestinations[4].image,
    images: [trendingDestinations[4].image, popularThings[7].image],
    duration: "6 hours",
    durationLabel: "6 hours",
    durationHours: 6,
    timeOfDay: "morning",
    group: "Small group",
    groupType: "Small group",
    groupSizeMax: 8,
    languages: ["English", "Indonesian"],
    price: 52.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.8,
    reviews: 142,
    features: ["hotelPickup", "freeCancellation", "instantConfirmation", "localGuide"],
    highlights: [
      "Tibumana and Tukad Cepung cavern waterfall swim",
      "Trek through untouched bamboo forests and cacao groves",
      "Traditional Balinese temple blessing ceremony",
      "Riverside lunch with organic farm-to-table Balinese dishes",
    ],
    included: [
      "Ubud and south Bali hotel pickup and drop-off",
      "Local Balinese eco-trekking guide",
      "All waterfall entrance tickets and temple donation sarongs",
      "Full Indonesian organic lunch and spring water",
    ],
    excluded: ["Personal shopping", "Driver tips"],
    meetingPoint: "Hotel pickup included across Ubud, Sanur, and Seminyak",
    cancellationPolicy: "Free cancellation up to 24 hours before start.",
    schedule: ["07:30 AM"],
    whatToBring: "Change of clothes, water shoes or grip sandals, towel, insect repellent.",
    featured: true,
    popular: true,
  },
  {
    id: "tokyo-night-food",
    slug: "tokyo-shinjuku-yakitori-ramen-night",
    title: "Shinjuku izakaya, yakitori & ramen night food crawl",
    description:
      "Navigate the smoky lantern-lit alleys of Omoide Yokocho and Golden Gai. Savor charcoal-grilled yakitori skewers, sample craft sake, and finish with a steaming bowl of artisan tonkotsu ramen.",
    location: "Tokyo, Japan",
    destination: "Tokyo",
    country: "Japan",
    category: "Food",
    image: trendingDestinations[6].image,
    images: [trendingDestinations[6].image, popularThings[0].image],
    duration: "3.5 hours",
    durationLabel: "3.5 hours",
    durationHours: 3.5,
    timeOfDay: "evening",
    group: "Small group",
    groupType: "Small group",
    groupSizeMax: 8,
    languages: ["English", "Japanese"],
    price: 65.0,
    // TODO(compliance): confirm the original price was genuinely charged before launch, per applicable consumer-protection rules
    // TODO(api): Sync izakaya partner promotion with Shinjuku culinary guides
    originalPrice: 80.0,
    validUntil: "2026-11-30",
    dealLabel: "Izakaya partner rate",
    terms: ["Valid for midweek tours", "All 3 izakaya courses included"],
    currency: "USD",
    rating: 4.9,
    reviews: 210,
    features: ["localGuide", "mobileTicket", "instantConfirmation", "freeCancellation"],
    highlights: [
      "Atmospheric walk through 'Memory Lane' (Omoide Yokocho) backstreets",
      "3 authentic izakaya stops featuring grilled yakitori, gyoza, and local pickles",
      "Comparative tasting of 3 distinct regional Japanese sakes",
      "Michelin Bib Gourmand artisan ramen tasting to finish the evening",
    ],
    included: [
      "Bilingual Tokyo resident gastronomy guide",
      "All food tastings equivalent to a generous multi-course dinner",
      "3 alcoholic or non-alcoholic beverage drinks",
    ],
    excluded: ["Additional drinks beyond package", "Train fares"],
    meetingPoint: "Shinjuku Station West Exit Police Box, Tokyo",
    cancellationPolicy: "Free cancellation up to 48 hours before tour start for a full refund.",
    schedule: ["05:30 PM", "07:00 PM"],
    whatToBring: "Comfortable shoes, appetite, cash for optional extra drinks.",
    featured: true,
    popular: true,
  },
  {
    id: "rome-colosseum-night",
    slug: "rome-colosseum-moonlight-underground",
    title: "Colosseum by moonlight & underground chambers",
    description:
      "Enter the mighty Roman amphitheater after public daytime closing hours. Walk across the arena floor under the stars and descend into the subterranean hypogeum where gladiators prepared.",
    location: "Rome, Italy",
    destination: "Rome",
    country: "Italy",
    category: "History",
    image: trendingDestinations[2].image,
    images: [trendingDestinations[2].image, popularThings[1].image],
    duration: "2.5 hours",
    durationLabel: "2.5 hours",
    durationHours: 2.5,
    timeOfDay: "evening",
    group: "Small group",
    groupType: "Small group",
    groupSizeMax: 12,
    languages: ["English", "Italian"],
    price: 79.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.9,
    reviews: 188,
    features: ["instantConfirmation", "localGuide", "mobileTicket"],
    highlights: [
      "Exclusive night-time entry to the Colosseum without daytime crowds",
      "Access to the underground hypogeum and gladiator staging areas",
      "Full moon views over the Forum and Arch of Constantine",
      "Passionate narrative by a licensed classical archaeologist",
    ],
    included: [
      "Official VIP after-hours Colosseum and underground entry permits",
      "Licensed expert archeologist escort",
      "Whisper headsets for clear commentary",
    ],
    excluded: ["Hotel transport", "Food and drinks"],
    meetingPoint: "Colosseo Metro Station Upper Level Exit, Rome",
    cancellationPolicy: "Non-refundable once reserved due to state monument entry regulations.",
    schedule: ["08:00 PM", "08:45 PM"],
    whatToBring: "Government-issued passport or photo ID matching reservation, comfortable shoes.",
    featured: true,
    popular: true,
  },
  {
    id: "singapore-gardens-night",
    slug: "singapore-cloud-forest-supertree-light",
    title: "Gardens by the Bay biodome & Supertree light show",
    description:
      "Explore the misty, climate-controlled mountain biodomes of the Cloud Forest, stroll along the elevated OCBC Skyway, and witness the dazzling Garden Rhapsody musical light show.",
    location: "Singapore",
    destination: "Singapore",
    country: "Singapore",
    category: "Sightseeing",
    image: trendingDestinations[1].image,
    images: [trendingDestinations[1].image, popularThings[0].image],
    duration: "3 hours",
    durationLabel: "3 hours",
    durationHours: 3,
    timeOfDay: "evening",
    group: "Small group",
    groupType: "Small group",
    groupSizeMax: 12,
    languages: ["English", "Mandarin"],
    price: 45.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.7,
    reviews: 165,
    features: ["instantConfirmation", "localGuide", "mobileTicket", "freeCancellation"],
    highlights: [
      "Fast-track entry into the Cloud Forest & Flower Dome conservatories",
      "Walk beneath the 35-meter indoor waterfall shrouded in tropical mist",
      "OCBC Skyway elevated suspension bridge stroll through Supertree tops",
      "Reserved prime lawn seating for the Garden Rhapsody evening light show",
    ],
    included: [
      "All conservatory admissions and Skyway access pass",
      "Local botanical guide with audio receivers",
      "Complimentary chilled tropical beverage",
    ],
    excluded: ["Hotel pickup", "Dinner"],
    meetingPoint: "Gardens by the Bay Visitor Centre Main Lobby, Singapore",
    cancellationPolicy: "Free cancellation up to 24 hours before tour start for a full refund.",
    schedule: ["05:00 PM"],
    whatToBring: "Light jacket for cool Cloud Forest biodome, smartphone/camera.",
    featured: false,
    popular: true,
  },
];

// Factual operational stats
export const experienceStats = [
  { value: "12", label: "Vetted global hubs" },
  { value: "100%", label: "Verified native local hosts" },
  { value: "Small group", label: "Intimate group pacing" },
  { value: "24/7", label: "Human support hotline" },
];

// Collections defined by functional filter rules
export const collections = [
  {
    id: "first-time-bali",
    title: "First time in Bali",
    text: "The essential jungle, waterfall, and holy spring experiences.",
    image: trendingDestinations[4].image,
    filter: { destination: "Bali" },
  },
  {
    id: "after-dark",
    title: "After dark & evening stories",
    text: "Night market crawls, colosseum moonlight tours, and sunset walks.",
    image: trendingDestinations[15].image,
    filter: { timeOfDay: "evening" },
  },
  {
    id: "local-authentic",
    title: "Local & authentic culture",
    text: "Cave villages, artisan workshops, and living history traditions.",
    image: trendingDestinations[7].image,
    filter: { category: "Culture" },
  },
  {
    id: "water-coastal",
    title: "Water & coastal escapes",
    text: "Sea cave canoeing, coral reef diving, and island cruising.",
    image: trendingDestinations[14].image,
    filter: { category: "Water" },
  },
];

export const experienceFaqs = [
  [
    "How do short experiences differ from multi-day tours?",
    "Experiences are focused, half-day or 2-to-6 hour activities (such as food crawls, sea cave canoeing, or museum walks) that you add to an itinerary. You can book them individually to enrich days when you want guided insight.",
  ],
  [
    "What is the cancellation policy for experiences?",
    "Most of our activities feature free cancellation up to 24 or 48 hours before the start time. The exact policy is displayed transparently on each experience page before you confirm.",
  ],
  [
    "How does the 'Build Your Perfect Day' planner work?",
    "Select your destination to preview morning, afternoon, and evening experiences. You can shortlist your favorite activities to see the estimated schedule and total price, then send it directly to our coordinators to orchestrate the bookings.",
  ],
  [
    "Can experiences be booked as private excursions for our party?",
    "Yes. Almost all experiences offer private buyout options for families, couples, or team retreats. Use our 'Request private experience' form to receive custom pricing.",
  ],
  [
    "Are local host credentials verified?",
    "Every host on Viatours is an accredited guide, licensed captain, or certified specialist who undergoes identity, safety, and operational vetting.",
  ],
];

export const faqs = experienceFaqs;

export { popularThings, trendingDestinations };
