"use client";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { FiArrowRight, FiClock, FiHeart, FiMapPin, FiStar } from "react-icons/fi";
const TourCard = ({ tour }) => {
  const [saved, setSaved] = useState(false);
  const discount = tour.originalPrice ? Math.round((1 - Number(tour.price) / tour.originalPrice) * 100) : null;
  return <article className="group overflow-hidden rounded-2xl border border-gray6 bg-white transition-all duration-300 hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[1.35] overflow-hidden"><Image src={tour.image} alt={tour.title + " in " + tour.location} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover transition-transform duration-500 group-hover:scale-105" />{discount && <span className="absolute left-4 top-4 rounded-full bg-accent px-3 py-1 text-xs font-semibold text-white">-${discount}%</span>}<button type="button" onClick={() => setSaved((value) => !value)} aria-label={(saved ? "Remove " : "Save ") + tour.title + " from wishlist"} aria-pressed={saved} className={"absolute right-4 top-4 flex h-10 w-10 items-center justify-center rounded-full bg-white/90 " + (saved ? "text-accent" : "text-dark hover:text-accent")}><FiHeart className={saved ? "fill-current" : ""} /></button></div><div className="p-5"><div className="flex items-center justify-between gap-3"><p className="body5 font-medium uppercase tracking-[1px] text-accent">{tour.category}</p><span className="body5 flex items-center gap-1 text-text-secondary"><FiClock /> {tour.days} days</span></div><h3 className="title2 mt-2 line-clamp-2 min-h-[48px] text-dark">{tour.title}</h3><p className="body4 mt-2 flex items-center gap-1.5 text-text-secondary"><FiMapPin className="text-accent" /> {tour.location}</p><div className="mt-4 flex items-center gap-2 border-t border-gray6 pt-4"><span className="flex items-center gap-1 text-sm font-semibold text-dark"><FiStar className="fill-[#f5b544] text-[#f5b544]" /> {tour.rating}</span><span className="body5 text-text-secondary">({tour.reviews} reviews)</span><span className="ml-auto body5 text-text-secondary">{tour.group}</span></div><div className="mt-4 flex items-end justify-between gap-3"><div><span className="body5 block text-text-secondary">From</span>{tour.originalPrice && <span className="body5 mr-2 text-text-secondary line-through">${tour.originalPrice.toFixed(0)}</span>}<span className="title1 text-dark">${tour.price}</span></div><Link href={"/tours/" + tour.id} className="title4 inline-flex items-center gap-1 rounded-xl bg-dark px-4 py-3 text-white hover:bg-accent">View tour <FiArrowRight /></Link></div></div></article>;
};
export default TourCard;
