"use client";
import { FiSearch, FiX } from "react-icons/fi";
const TourFilters = ({ filters, setFilters, destinations = [], categories = [], onClose, mobile = false }) => <div className="space-y-6">
  {mobile && <div className="flex items-center justify-between border-b border-gray6 pb-5"><h3 className="title1 text-dark">Filter tours</h3><button type="button" onClick={onClose} aria-label="Close filters" className="rounded-full p-2 text-dark"><FiX /></button></div>}
  <label className="block"><span className="title4 text-dark">Search tours</span><div className="mt-2 flex items-center gap-2 rounded-xl border border-gray5 px-3 py-3"><FiSearch className="text-text-secondary" /><input value={filters.search} onChange={(event) => setFilters((state) => ({ ...state, search: event.target.value }))} placeholder="Search by destination" className="body4 min-w-0 w-full text-dark outline-none" /></div></label>
  <label className="block"><span className="title4 text-dark">Destination</span><select value={filters.destination} onChange={(event) => setFilters((state) => ({ ...state, destination: event.target.value }))} className="body4 mt-2 w-full rounded-xl border border-gray5 bg-white px-3 py-3 text-dark outline-none"><option value="all">All destinations</option>{destinations.map((location) => <option key={location} value={location}>{location}</option>)}</select></label>
  <label className="block"><span className="title4 text-dark">Travel style</span><select value={filters.category} onChange={(event) => setFilters((state) => ({ ...state, category: event.target.value }))} className="body4 mt-2 w-full rounded-xl border border-gray5 bg-white px-3 py-3 text-dark outline-none"><option value="all">All styles</option>{categories.map((category) => <option key={category} value={category}>{category}</option>)}</select></label>
  <label className="block"><div className="flex justify-between"><span className="title4 text-dark">Maximum price</span><span className="body4 text-accent">${filters.maxPrice}</span></div><input type="range" min="99" max="900" step="25" value={filters.maxPrice} onChange={(event) => setFilters((state) => ({ ...state, maxPrice: event.target.value }))} className="mt-4 w-full accent-[#eb662b]" /></label>
  <button type="button" onClick={() => setFilters({ search: "", destination: "all", category: "all", maxPrice: 900 })} className="title4 text-accent hover:underline">Clear all filters</button>
</div>;
export default TourFilters;
