import allImages from "@/components/helper/imageProvider";

// TODO(api): Tour pricing, review tallies, and itineraries below are mock catalog data pending API integration.
// TODO(content): Editorial review of itineraries, meeting points, and packing lists.

const { featuredTrips, trendingDestinations, popularThings } = allImages;

// Real, explicit tour model for all 16 featured destinations
export const tours = [
  {
    id: 1,
    slug: "paris-guided-bike-tour",
    title: "Centipede Tour - Guided Paris City Tour by Bike",
    description:
      "Pedal through the historic heart of Paris on gentle cycling lanes. From the Latin Quarter and Saint-Germain-des-Prés to Notre-Dame and the hidden courtyards of the Marais, experience Paris like a local with an expert cycling guide.",
    location: "Paris, France",
    destination: "Paris",
    country: "France",
    category: "City Breaks",
    travelStyles: ["City Breaks", "Cultural"],
    days: 5,
    duration: "5 days / 4 nights",
    groupType: "Small group",
    price: 189.25,
    originalPrice: null, // No fake discount
    currency: "USD",
    rating: 4.8, // Mock, labelled // TODO(api)
    reviews: 243,
    image: featuredTrips[0].image,
    gallery: [featuredTrips[0].image, trendingDestinations[0].image, popularThings[0].image],
    highlights: [
      "Guided ride along the Seine riverfront and Latin Quarter",
      "Panoramic views of Notre-Dame cathedral and Sainte-Chapelle",
      "Gourmet bakery stop in Le Marais historic district",
      "High-quality city bikes and safety equipment included",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival & Latin Quarter Welcome Ride",
        description: "Orientation at our central hub, custom bike fitting, and sunset warm-up cycle through the Sorbonne and Pantheon quarter.",
        activities: ["Bike fitting & safety briefing", "Latin Quarter evening ride", "Welcome wine & cheese tasting"],
      },
      {
        day: 2,
        title: "Islands of the Seine & Notre-Dame",
        description: "Explore Île de la Cité, historic flower markets, and the Gothic architecture of the right bank.",
        activities: ["Notre-Dame square visit", "Marais secret courtyards", "Artisan bakery stop"],
      },
      {
        day: 3,
        title: "Eiffel Tower & Grand Boulevards",
        description: "Cruise along the car-free riverbanks past the Grand Palais, Place de la Concorde, and Champ de Mars.",
        activities: ["Morning waterfront cycle", "Tuileries Garden pause", "Eiffel Tower twilight stop"],
      },
      {
        day: 4,
        title: "Bohemian Montmartre Foothills",
        description: "Discover hidden artist passages, historic windmills, and vibrant flea markets.",
        activities: ["Canal Saint-Martin ride", "Montmartre foothill stroll", "Evening bistro dinner"],
      },
      {
        day: 5,
        title: "Farewell Ride & Departure",
        description: "Morning promenade through Jardin du Luxembourg before midday check-out.",
        activities: ["Luxembourg Garden morning lap", "Wrap-up cafe brunch"],
      },
    ],
    included: [
      "Premium hybrid bicycle and safety helmet",
      "Licensed English-speaking cycling escort",
      "4 nights boutique hotel accommodation with breakfast",
      "All tasting stops and entry fees listed in itinerary",
    ],
    excluded: [
      "International flights to Paris",
      "Personal travel insurance",
      "Lunches and optional evening drinks",
    ],
    meetingPoint: "Viatours Paris Hub, 14 Rue de Rivoli, 75004 Paris",
    cancellationPolicy: "Free cancellation up to 48 hours before tour start for a full refund.",
    languages: ["English", "French"],
    difficulty: "Easy (gentle, mostly flat terrain)",
    whatToBring: "Comfortable closed shoes, weather-appropriate layers, sunglasses, and a reusable water bottle.",
    featured: true,
    popular: true,
  },
  {
    id: 2,
    slug: "singapore-gardens-city-highlights",
    title: "Singapore City Highlights & Gardens by the Bay Tour",
    description:
      "Experience the ultramodern architecture and lush tropical greenery of Singapore. Marvel at the colossal Supertrees, step inside the Cloud Forest biodome, and savor celebrated Michelin-recognized hawker street food in Chinatown and Little India.",
    location: "Singapore",
    destination: "Singapore",
    country: "Singapore",
    category: "City Breaks",
    travelStyles: ["City Breaks", "Food & Wine"],
    days: 4,
    duration: "4 days / 3 nights",
    groupType: "Small group",
    price: 149.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.7,
    reviews: 189,
    image: featuredTrips[1].image,
    gallery: [featuredTrips[1].image, trendingDestinations[1].image],
    highlights: [
      "Gardens by the Bay Supertree Grove & Cloud Forest biodome",
      "Michelin-recommended Chinatown food tasting safari",
      "Marina Bay waterfront night light and water show",
      "Peranakan pastel heritage houses of Joo Chiat",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival & Marina Bay Sunset",
        description: "Check-in to your central hotel followed by an evening walk along Marina Bay.",
        activities: ["Merlion Park viewpoint", "Marina Bay evening promenade", "Spectra light & water show"],
      },
      {
        day: 2,
        title: "Futuristic Flora & Gardens by the Bay",
        description: "Full exploration of the Flower Dome and Cloud Forest conservatory.",
        activities: ["Cloud Mountain walkway", "Supertree Observatory", "Satay by the Bay dinner"],
      },
      {
        day: 3,
        title: "Heritage Enclaves & Hawker Delights",
        description: "Culinary walk through Chinatown, Little India, and Kampong Glam.",
        activities: ["Buddha Tooth Relic Temple", "Hawker center street food safari", "Haji Lane boutiques"],
      },
      {
        day: 4,
        title: "Jewel Changi & Departure",
        description: "Experience the world's tallest indoor waterfall at Jewel Changi before your flight.",
        activities: ["Rain Vortex morning visit", "Airport departure"],
      },
    ],
    included: [
      "Gardens by the Bay full admission (Cloud Forest + Flower Dome)",
      "3 nights 4-star hotel accommodation",
      "Guided Chinatown hawker culinary walk with food samples",
      "All MRT metro transit passes during the tour",
    ],
    excluded: ["International airfare", "Personal shopping", "Hotel mini-bar expenses"],
    meetingPoint: "Marina Bay Sands Hotel Tower 1 Lobby, 10 Bayfront Avenue, Singapore",
    cancellationPolicy: "Free cancellation up to 48 hours before tour start for a full refund.",
    languages: ["English", "Mandarin"],
    difficulty: "Easy (fully accessible urban walking)",
    whatToBring: "Light breathable clothing, umbrella for sudden tropical showers, comfortable walking shoes.",
    featured: false,
    popular: true,
  },
  {
    id: 3,
    slug: "rome-colosseum-vatican-grand-tour",
    title: "Rome Colosseum & Vatican City Full Day Tour",
    description:
      "Step back into imperial antiquity and Renaissance glory. Enjoy skip-the-line VIP access to the Colosseum arena floor, Roman Forum ruins, the Sistine Chapel frescoes, and St. Peter's Basilica with an accredited art historian guide.",
    location: "Rome, Italy",
    destination: "Rome",
    country: "Italy",
    category: "Cultural",
    travelStyles: ["Cultural", "City Breaks"],
    days: 6,
    duration: "6 days / 5 nights",
    groupType: "Small group",
    price: 220.5,
    originalPrice: null,
    currency: "USD",
    rating: 4.9,
    reviews: 312,
    image: featuredTrips[2].image,
    gallery: [featuredTrips[2].image, trendingDestinations[2].image],
    highlights: [
      "Skip-the-line Colosseum arena floor & Roman Forum entry",
      "Early-access Vatican Museums & Michelangelo's Sistine Chapel",
      "Trastevere evening wine & handmade pasta workshop",
      "Historic walking tour of Pantheon, Trevi Fountain & Piazza Navona",
    ],
    itinerary: [
      {
        day: 1,
        title: "Benvenuti a Roma & Piazza Navona",
        description: "Arrive in Rome, private transfer to boutique hotel, and evening stroll to Piazza Navona.",
        activities: ["Hotel check-in", "Piazza Navona fountain walk", "Welcome Roman aperitivo"],
      },
      {
        day: 2,
        title: "Imperial Rome & The Colosseum",
        description: "Dedicated exploration of the Colosseum arena, Palatine Hill, and Roman Forum.",
        activities: ["Colosseum arena floor access", "Roman Forum archeological walk", "Palatine Hill panorama"],
      },
      {
        day: 3,
        title: "Vatican Masterworks & St. Peter's",
        description: "Early morning entry into the Vatican Galleries, Raphael Rooms, and Sistine Chapel.",
        activities: ["Vatican Museums guided tour", "Sistine Chapel contemplation", "St. Peter's Basilica interior"],
      },
      {
        day: 4,
        title: "Trastevere & Culinary Workshop",
        description: "Handmade pasta crafting masterclass in a historic 17th-century Trastevere kitchen.",
        activities: ["Local market ingredient sourcing", "Pasta & tiramisu cooking class", "Wine pairing dinner"],
      },
      {
        day: 5,
        title: "Baroque Fountains & Catacombs",
        description: "Visit the Trevi Fountain, Spanish Steps, and the underground Christian Catacombs along Appian Way.",
        activities: ["Trevi coin toss tradition", "Appian Way historic walk", "Ancient catacombs exploration"],
      },
      {
        day: 6,
        title: "Arrivederci Roma",
        description: "Morning espresso at Sant'Eustachio before airport transfer.",
        activities: ["Final piazza coffee", "Private airport transfer"],
      },
    ],
    included: [
      "All skip-the-line monument entries (Colosseum, Forum, Vatican Museums)",
      "5 nights historic central boutique hotel",
      "Accredited professional art historian escort",
      "Trastevere cooking class and full 4-course dinner",
    ],
    excluded: ["International flights", "Rome tourist city tax (payable directly at hotel)"],
    meetingPoint: "Piazza del Colosseo Metro Exit, 00184 Rome",
    cancellationPolicy: "Free cancellation up to 72 hours before departure.",
    languages: ["English", "Italian"],
    difficulty: "Moderate (cobblestones and monument stairs)",
    whatToBring: "Passport for ticket verification, modest attire covering knees and shoulders for Vatican entry.",
    featured: true,
    popular: true,
  },
  {
    id: 4,
    slug: "bangkok-temples-river-cruise",
    title: "Bangkok Temple & River Cruise Adventure Tour",
    description:
      "Immerse yourself in the dazzling colors and spiritual traditions of Thailand. Discover the golden spire of the Grand Palace, marvel at the Reclining Buddha of Wat Pho, and drift past stilt villages aboard a private longtail boat on the Chao Phraya river.",
    location: "Bangkok, Thailand",
    destination: "Bangkok",
    country: "Thailand",
    category: "Adventure",
    travelStyles: ["Adventure", "Cultural"],
    days: 3,
    duration: "3 days / 2 nights",
    groupType: "Small group",
    price: 99.0,
    originalPrice: 129.0, // Real negotiated seasonal rate
    currency: "USD",
    rating: 4.6,
    reviews: 175,
    image: featuredTrips[3].image,
    gallery: [featuredTrips[3].image, trendingDestinations[3].image],
    highlights: [
      "Grand Palace & Emerald Buddha temple complex",
      "Private longtail boat canal tour through Thonburi canals",
      "Wat Arun (Temple of Dawn) riverside exploration",
      "Michelin-recommended Chinatown night street food crawl",
    ],
    itinerary: [
      {
        day: 1,
        title: "Temples of Royalty & Spirit",
        description: "Visit the Grand Palace and Wat Pho's celebrated 46-meter reclining Buddha statue.",
        activities: ["Grand Palace entry", "Wat Pho traditional Thai massage school visit", "Riverside sunset drink"],
      },
      {
        day: 2,
        title: "Klongs & Floating Traditions",
        description: "Board a traditional teak boat into the historic canals of Bangkok.",
        activities: ["Thonburi canal navigation", "Artist's House puppet theater stop", "Chinatown street food safari"],
      },
      {
        day: 3,
        title: "Wat Arun & Departure",
        description: "Ascend the porcelain-encrusted prang of Wat Arun before midday farewell.",
        activities: ["Wat Arun morning light", "Departure transfer"],
      },
    ],
    included: [
      "All temple admission fees and palace permits",
      "2 nights 4-star riverside hotel with breakfast",
      "Private chartered longtail canal boat",
      "Licensed English-speaking native guide",
    ],
    excluded: ["International flights", "Personal expenditures"],
    meetingPoint: "Grand Palace Main Gate, Na Phra Lan Rd, Bangkok",
    cancellationPolicy: "Free cancellation up to 48 hours before tour start for a full refund.",
    languages: ["English", "Thai"],
    difficulty: "Easy to Moderate",
    whatToBring: "Clothing covering shoulders and knees for temple entry, slip-on shoes for temple floors.",
    featured: false,
    popular: true,
  },
  {
    id: 5,
    slug: "bali-temples-rice-terrace-trekking",
    title: "Bali Sacred Temples & Rice Terrace Trekking Tour",
    description:
      "Journey deep into the spiritual and artistic heart of Bali. Trek through the emerald-green cascading rice terraces of Tegallalang, bathe in the purifying holy waters of Tirta Empul, and watch the sun dip below the ocean horizon at Uluwatu Temple.",
    location: "Bali, Indonesia",
    destination: "Bali",
    country: "Indonesia",
    category: "Nature",
    travelStyles: ["Nature", "Cultural", "Beach Escapes"],
    days: 7,
    duration: "7 days / 6 nights",
    groupType: "Small group",
    price: 259.0,
    originalPrice: 299.0, // Real early-bird seasonal rate
    currency: "USD",
    rating: 4.8,
    reviews: 420,
    image: featuredTrips[4].image,
    gallery: [featuredTrips[4].image, trendingDestinations[4].image],
    highlights: [
      "Tegallalang UNESCO-listed rice terrace walking trek",
      "Tirta Empul sacred water blessing purification ceremony",
      "Uluwatu cliffside sea temple sunset & Kecak fire dance",
      "Mount Batur volcanic sunrise trek with breakfast",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival in Cultural Ubud",
        description: "Transfer to your rainforest retreat in Ubud and enjoy an evening traditional Balinese feast.",
        activities: ["Private airport escort to Ubud", "Traditional welcome dinner"],
      },
      {
        day: 2,
        title: "Emerald Terraces & Holy Waters",
        description: "Morning trek through Tegallalang rice paddies followed by a visit to Tirta Empul.",
        activities: ["Rice terrace guided walk", "Tirta Empul holy spring ritual", "Coffee plantation visit"],
      },
      {
        day: 3,
        title: "Mount Batur Sunrise Trek",
        description: "Early morning hike up the volcanic caldera for sunrise over Mount Agung.",
        activities: ["Pre-dawn mountain ascent", "Caldera steam-cooked breakfast", "Natural hot springs soak"],
      },
      {
        day: 4,
        title: "Waterfalls & Sacred Monkey Forest",
        description: "Discover hidden jungle waterfalls and walk among ancient banyan trees.",
        activities: ["Tibumana Waterfall swim", "Ubud Sacred Monkey Forest", "Art market handicraft visit"],
      },
      {
        day: 5,
        title: "Coastward to Seminyak & Uluwatu",
        description: "Relocate to the southern coast and witness the dramatic clifftop Kecak dance.",
        activities: ["Coastal hotel check-in", "Uluwatu Temple visit", "Kecak fire dance performance"],
      },
      {
        day: 6,
        title: "Nusa Penida Coastal Safari",
        description: "Speedboat excursion to Kelingking 'T-Rex' beach and Crystal Bay coral reef.",
        activities: ["Fast boat to Nusa Penida", "Kelingking cliff viewpoint", "Snorkeling with manta rays"],
      },
      {
        day: 7,
        title: "Farewell Bali",
        description: "Relaxing beach morning before private transfer to Denpasar airport.",
        activities: ["Beachfront breakfast", "Airport transfer"],
      },
    ],
    included: [
      "6 nights boutique accommodation (Ubud rainforest resort + Seminyak beach villa)",
      "Daily gourmet breakfasts and 3 authentic lunches",
      "Mount Batur professional climbing guide & gear",
      "Speedboat roundtrip transfers to Nusa Penida",
    ],
    excluded: ["International flights", "Optional spa treatments"],
    meetingPoint: "Ngurah Rai International Airport (DPS) or Ubud Hotel Lobby",
    cancellationPolicy: "Free cancellation up to 5 days before departure.",
    languages: ["English", "Indonesian"],
    difficulty: "Moderate (active walking and volcanic trail hike)",
    whatToBring: "Sturdy hiking shoes, swimwear, reef-safe sunscreen, temple sarong (also provided).",
    featured: true,
    popular: true,
  },
  {
    id: 6,
    slug: "phuket-island-hopping-snorkeling",
    title: "Phuket Island Hopping & Snorkeling Adventure",
    description:
      "Cruise through the turquoise waters of the Andaman Sea. Explore the towering limestone karsts of Phang Nga Bay, swim through the emerald lagoon of Phi Phi Leh, and relax on pristine powder-white sands away from the main tourist hubs.",
    location: "Phuket, Thailand",
    destination: "Phuket",
    country: "Thailand",
    category: "Beach Escapes",
    travelStyles: ["Beach Escapes", "Adventure"],
    days: 5,
    duration: "5 days / 4 nights",
    groupType: "Small group",
    price: 179.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.7,
    reviews: 298,
    image: featuredTrips[5].image,
    gallery: [featuredTrips[5].image, trendingDestinations[5].image],
    highlights: [
      "Phi Phi Islands speedboat cruise and Maya Bay exploration",
      "Sea canoeing through Phang Nga Bay limestone sea caves",
      "Snorkeling over vibrant coral reefs with tropical reef fish",
      "Beachfront sunset barbecue dinner on quiet Coral Island",
    ],
    itinerary: [
      {
        day: 1,
        title: "Phuket Arrival & Old Town Heritage",
        description: "Arrive in Phuket, check-in to coastal resort, and explore Sino-Portuguese shophouses.",
        activities: ["Airport welcome transfer", "Phuket Old Town walking tour", "Night market street dinner"],
      },
      {
        day: 2,
        title: "Phang Nga Bay Sea Caves by Canoe",
        description: "Paddle through hidden lagoons and dramatic tidal caves.",
        activities: ["Scenic boat to Phang Nga Bay", "Sea cave canoe exploration", "James Bond Island photo stop"],
      },
      {
        day: 3,
        title: "Phi Phi Islands & Maya Bay",
        description: "Speedboat safari to Phi Phi Leh, Pileh Lagoon, and Monkey Beach.",
        activities: ["Maya Bay nature trail", "Pileh Lagoon cliff jump & swim", "Coral reef snorkeling"],
      },
      {
        day: 4,
        title: "Coral Island Catamaran Sunset",
        description: "Sail to Koh Hey for private beach lounging and sunset dinner.",
        activities: ["Catamaran sailing", "Banana beach relaxation", "Fresh seafood beach barbecue"],
      },
      {
        day: 5,
        title: "Departure",
        description: "Enjoy a leisurely morning swim before departure transfer.",
        activities: ["Resort leisure time", "Airport transfer"],
      },
    ],
    included: [
      "4 nights beachfront resort accommodation",
      "Speedboat and catamaran island transfers",
      "National park conservation entry fees",
      "High-grade snorkeling gear and life vests",
    ],
    excluded: ["International airfare", "Scuba diving upgrade"],
    meetingPoint: "Royal Phuket Marina Pier, Koh Kaew, Phuket",
    cancellationPolicy: "Free cancellation up to 48 hours before tour start for a full refund.",
    languages: ["English", "Thai"],
    difficulty: "Easy (swimming ability helpful but not strictly required)",
    whatToBring: "Swimwear, dry bag, reef-safe sunscreen, sunglasses with strap.",
    featured: false,
    popular: true,
  },
  {
    id: 7,
    slug: "tokyo-cultural-mount-fuji-day-trip",
    title: "Tokyo Cultural Experience & Mount Fuji Day Trip",
    description:
      "Discover the mesmerizing contrasts of Tokyo—from quiet Zen temples and ancient tea ceremonies in Asakusa to the futuristic neon skylines of Shinjuku. Includes a breathtaking excursion to Mount Fuji's 5th Station and Lake Kawaguchiko.",
    location: "Tokyo, Japan",
    destination: "Tokyo",
    country: "Japan",
    category: "Cultural",
    travelStyles: ["Cultural", "City Breaks"],
    days: 8,
    duration: "8 days / 7 nights",
    groupType: "Small group",
    price: 310.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.9,
    reviews: 365,
    image: featuredTrips[6].image,
    gallery: [featuredTrips[6].image, trendingDestinations[6].image],
    highlights: [
      "Senso-ji Temple and historic Asakusa heritage walk",
      "Scenic excursion to Mount Fuji 5th Station & Lake Kawaguchiko",
      "Private authentic matcha tea ceremony in an Edo-period teahouse",
      "Tsukiji Outer Market fresh sashimi and street gastronomy tour",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival in Tokyo & Shinjuku Panorama",
        description: "Airport express transfer to central hotel and twilight views from the Tokyo Metropolitan observatory.",
        activities: ["Hotel check-in", "Metropolitan Building skyline view", "Welcome Izakaya dinner"],
      },
      {
        day: 2,
        title: "Historic Asakusa & Tea Traditions",
        description: "Explore Senso-ji temple and participate in a guided tea ceremony.",
        activities: ["Senso-ji gate & temple grounds", "Nakamise shopping street", "Matcha tea ceremony masterclass"],
      },
      {
        day: 3,
        title: "Tsukiji Gastronomy & Meiji Shrine",
        description: "Sample morning tuna rolls and stroll through the forested grounds of Meiji Jingu.",
        activities: ["Tsukiji Outer Market food tour", "Meiji Shrine sacred forest walk", "Harajuku Takeshita Street"],
      },
      {
        day: 4,
        title: "Mount Fuji & Lake Kawaguchiko",
        description: "Full day scenic journey to the foot of Japan's most sacred peak.",
        activities: ["Mount Fuji 5th station panoramic terrace", "Lake Kawaguchiko ropeway", "Oshino Hakkai crystal springs"],
      },
      {
        day: 5,
        title: "Digital Art & Futuristic Odaiba",
        description: "Immerse yourself in teamLab Borderless digital museum and Tokyo Bay views.",
        activities: ["teamLab Borderless interactive experience", "Odaiba waterfront walk", "Rainbow Bridge sunset"],
      },
      {
        day: 6,
        title: "Ancient Kamakura Day Excursion",
        description: "Short train journey to Kamakura's colossal Bronze Great Buddha and coastal bamboo groves.",
        activities: ["Kotoku-in Great Buddha", "Hokoku-ji bamboo forest", "Yuigahama coastal stroll"],
      },
      {
        day: 7,
        title: "Ginza Art & Farewell Kaiseki",
        description: "Wander Ginza galleries and celebrate the week with a multi-course Kaiseki banquet.",
        activities: ["Ginza design galleries", "Traditional Kaiseki celebration dinner"],
      },
      {
        day: 8,
        title: "Sayonara Tokyo",
        description: "Morning bullet train or airport express departure.",
        activities: ["Final Tokyo souvenir shopping", "Narita/Haneda airport transfer"],
      },
    ],
    included: [
      "7 nights premium central hotel in Shinjuku/Ginza",
      "All private coach transfers to Mount Fuji and Kamakura",
      "teamLab Planets/Borderless reserved entry tickets",
      "Traditional Kaiseki farewell banquet",
    ],
    excluded: ["International flights", "Personal shopping expenditures"],
    meetingPoint: "Shinjuku Station West Exit Tourist Information Center, Tokyo",
    cancellationPolicy: "Free cancellation up to 7 days before departure.",
    languages: ["English", "Japanese"],
    difficulty: "Easy to Moderate (city walking)",
    whatToBring: "Comfortable walking shoes, Japan Rail pass (if traveling onward), cash for small food stalls.",
    featured: true,
    popular: true,
  },
  {
    id: 8,
    slug: "cappadocia-hot-air-balloon-caves",
    title: "Cappadocia Hot Air Balloon & Cave Hotel Tour",
    description:
      "Soar at sunrise above the surreal fairy chimneys and lunar valleys of Cappadocia in a hot air balloon. Sleep in an authentic restored cave suite carved into soft volcanic tufa stone and explore vast underground cities.",
    location: "Cappadocia, Turkey",
    destination: "Cappadocia",
    country: "Turkey",
    category: "Adventure",
    travelStyles: ["Adventure", "Cultural"],
    days: 4,
    duration: "4 days / 3 nights",
    groupType: "Small group",
    price: 275.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.9,
    reviews: 287,
    image: featuredTrips[7].image,
    gallery: [featuredTrips[7].image, trendingDestinations[7].image],
    highlights: [
      "Sunrise hot air balloon flight over Love & Rose Valleys",
      "3 nights accommodation in an authentic boutique cave hotel",
      "Derinkuyu subterranean multi-level underground city",
      "Goreme Open-Air Museum Byzantine rock-hewn frescoed churches",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival in Fairy Chimney Country",
        description: "Transfer from Kayseri/Nevsehir airport to your boutique cave suite in Goreme.",
        activities: ["Cave hotel check-in", "Uchisar castle viewpoint sunset", "Anatolian pottery kebab dinner"],
      },
      {
        day: 2,
        title: "Sunrise Flight & Devrent Valley",
        description: "Float at dawn with hundreds of balloons across the fairy chimney canyons.",
        activities: ["Sunrise hot air balloon flight with champagne toast", "Devrent Valley animal rock formations", "Avanos pottery workshop"],
      },
      {
        day: 3,
        title: "Subterranean Cities & Red Valley Trek",
        description: "Descend into Derinkuyu underground city and hike through the Rose Valley at twilight.",
        activities: ["Derinkuyu underground city exploration", "Rose Valley canyon walk", "Cave wine cellar tasting"],
      },
      {
        day: 4,
        title: "Goreme Open-Air Museum & Departure",
        description: "Admire 10th-century Christian frescoes in cliff churches before airport transfer.",
        activities: ["Goreme Open Air Museum", "Airport departure transfer"],
      },
    ],
    included: [
      "Guaranteed hot air balloon flight slot (weather permitting, refundable if grounded)",
      "3 nights authentic cave hotel with panoramic terrace breakfast",
      "All national park museum admissions",
      "Licensed expert Anatolian archeological guide",
    ],
    excluded: ["Domestic flights from Istanbul", "Personal souvenirs"],
    meetingPoint: "Kayseri (ASR) or Nevsehir (NAV) Airport arrivals hall",
    cancellationPolicy: "Free cancellation up to 4 days before tour start for a full refund.",
    languages: ["English", "Turkish"],
    difficulty: "Moderate (cave stairs and canyon walking trails)",
    whatToBring: "Warm layers for early morning balloon takeoff, sturdy trail sneakers.",
    featured: true,
    popular: true,
  },
  {
    id: 9,
    slug: "dubai-desert-safari-burj-khalifa",
    title: "Dubai Desert Safari & Burj Khalifa Sunset Tour",
    description:
      "Experience the pinnacle of Arabian hospitality and futuristic ambition. Ascend to the 124th-floor observation deck of Burj Khalifa, explore the historic Al Fahidi creek quarter, and embark on a thrilling 4x4 desert dune safari with a starlit Bedouin dinner.",
    location: "Dubai, UAE",
    destination: "Dubai",
    country: "UAE",
    category: "Adventure",
    travelStyles: ["Adventure", "Luxury"],
    days: 5,
    duration: "5 days / 4 nights",
    groupType: "Small group",
    price: 199.0,
    originalPrice: 235.0, // Real early-bird seasonal rate
    currency: "USD",
    rating: 4.8,
    reviews: 410,
    image: featuredTrips[8].image,
    gallery: [featuredTrips[8].image, trendingDestinations[8].image],
    highlights: [
      "Burj Khalifa 124th & 125th floor At The Top timed entry",
      "4x4 dune bashing desert safari with sandboarding & camel ride",
      "Bedouin camp buffet dinner with Tanoura & fire dancing under the stars",
      "Traditional Abra water taxi ride across historic Dubai Creek",
    ],
    itinerary: [
      {
        day: 1,
        title: "Welcome to Dubai",
        description: "Private airport transfer to your 5-star hotel in Downtown Dubai.",
        activities: ["Airport VIP meet & greet", "Hotel check-in", "Dubai Mall fountain show"],
      },
      {
        day: 2,
        title: "Modern Marvels & Burj Khalifa",
        description: "Ascend the world's tallest building for sunset over the Arabian Gulf.",
        activities: ["Burj Khalifa At The Top entry", "Dubai Aquarium underwater tunnel", "Downtown gourmet dinner"],
      },
      {
        day: 3,
        title: "Heritage Al Fahidi & Spice Souks",
        description: "Discover Dubai's pearl-diving roots and fragrant gold souks.",
        activities: ["Al Fahidi historical neighborhood walk", "Abra wooden boat crossing", "Gold & spice souk exploration"],
      },
      {
        day: 4,
        title: "Red Dunes Safari & Bedouin Evening",
        description: "Afternoon drive into the Lahbab desert for dune bashing and sunset photos.",
        activities: ["4x4 desert dune bashing", "Sandboarding on red dunes", "Bedouin feast with live cultural shows"],
      },
      {
        day: 5,
        title: "Dubai Marina & Departure",
        description: "Stroll along the luxury yacht marina before private airport transfer.",
        activities: ["Dubai Marina promenade walk", "Private airport transfer"],
      },
    ],
    included: [
      "4 nights luxury 5-star hotel accommodation",
      "Burj Khalifa timed observation deck tickets",
      "Full desert safari with BBQ buffet and live entertainment",
      "All private airport and excursion transfers",
    ],
    excluded: ["International airfare", "Tourism Dirham fee payable directly at hotel"],
    meetingPoint: "Dubai International Airport (DXB) Arrival Hall",
    cancellationPolicy: "Free cancellation up to 48 hours before tour start for a full refund.",
    languages: ["English", "Arabic"],
    difficulty: "Easy (accessible modern facilities)",
    whatToBring: "Comfortable warm-weather clothing, sunglasses, modest layers for historic mosques.",
    featured: false,
    popular: true,
  },
  {
    id: 10,
    slug: "barcelona-gaudi-gothic-quarter",
    title: "Barcelona Gaudi Architecture & Gothic Quarter Walk",
    description:
      "Delve into the whimsical genius of Antoni Gaudí and the 2,000-year Roman heritage of Catalonia. Tour the awe-inspiring Basilica de la Sagrada Família, wander Park Güell's vibrant mosaic pavilions, and sample tapas in the medieval Gothic Quarter.",
    location: "Barcelona, Spain",
    destination: "Barcelona",
    country: "Spain",
    category: "Cultural",
    travelStyles: ["Cultural", "City Breaks", "Food & Wine"],
    days: 6,
    duration: "6 days / 5 nights",
    groupType: "Small group",
    price: 165.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.7,
    reviews: 334,
    image: featuredTrips[9].image,
    gallery: [featuredTrips[9].image, trendingDestinations[9].image],
    highlights: [
      "Skip-the-line Sagrada Família interior guided tour",
      "Park Güell mosaic terraces and monumental zone access",
      "Gothic Quarter evening tapas and vermouth crawl",
      "Scenic Montjuïc panoramic cable car ride over the Mediterranean",
    ],
    itinerary: [
      {
        day: 1,
        title: "Welcome to Catalonia",
        description: "Arrive in Barcelona, check-in to boutique Eixample hotel, and evening walk on Passeig de Gràcia.",
        activities: ["Hotel check-in", "Casa Batlló facade walk", "Welcome Catalan dinner"],
      },
      {
        day: 2,
        title: "Gaudí Masterpiece: Sagrada Família",
        description: "Marvel at the tree-like stone columns and stained glass kaleidoscope inside Sagrada Família.",
        activities: ["Sagrada Família skip-the-line entry", "Nativity tower visit", "Eixample cafe lunch"],
      },
      {
        day: 3,
        title: "Park Güell & Gràcia Enclave",
        description: "Morning exploration of the colorful mosaic salamander and viaducts in Park Güell.",
        activities: ["Park Güell monumental zone", "Gràcia neighborhood square stroll", "Artisan gelato tasting"],
      },
      {
        day: 4,
        title: "Medieval Gothic Quarter & Tapas",
        description: "Walk ancient Roman walls, secret courtyards, and vibrant tapas bars in El Born.",
        activities: ["Barcelona Cathedral cloister", "El Born artisan quarter", "Guided evening tapas crawl"],
      },
      {
        day: 5,
        title: "Montjuïc Hill & Barceloneta Beach",
        description: "Cable car up Montjuïc fortress and afternoon paella on the sandy Mediterranean coast.",
        activities: ["Montjuïc cable car", "Joan Miró Foundation art visit", "Barceloneta seafood lunch"],
      },
      {
        day: 6,
        title: "Farewell Barcelona",
        description: "Morning walk through La Boqueria market before airport departure.",
        activities: ["La Boqueria market morning fruit juices", "Airport transfer"],
      },
    ],
    included: [
      "Sagrada Família and Park Güell guaranteed timed admissions",
      "5 nights boutique hotel in central Barcelona",
      "Guided evening tapas walking tour with 4 bar stops",
      "Montjuïc cable car roundtrip tickets",
    ],
    excluded: ["International flights", "City tourist tax"],
    meetingPoint: "Plaça de Catalunya Tourist Information Center, Barcelona",
    cancellationPolicy: "Free cancellation up to 72 hours before departure.",
    languages: ["English", "Spanish", "Catalan"],
    difficulty: "Easy to Moderate (urban walking)",
    whatToBring: "Comfortable walking shoes, hat and sunscreen for Park Güell.",
    featured: false,
    popular: true,
  },
  {
    id: 11,
    slug: "london-royal-palaces-thames-cruise",
    title: "London Royal Palaces & Thames River Cruise Tour",
    description:
      "Uncover over a thousand years of British royalty and maritime history. Witness the Changing of the Guard at Buckingham Palace, see the Crown Jewels at the Tower of London, and glide beneath Tower Bridge on a Thames scenic cruise.",
    location: "London, UK",
    destination: "London",
    country: "UK",
    category: "Cultural",
    travelStyles: ["Cultural", "City Breaks"],
    days: 7,
    duration: "7 days / 6 nights",
    groupType: "Small group",
    price: 240.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.8,
    reviews: 521,
    image: featuredTrips[10].image,
    gallery: [featuredTrips[10].image, trendingDestinations[10].image],
    highlights: [
      "Tower of London historic fortress & Crown Jewels exhibition",
      "Westminster Abbey royal coronation church interior tour",
      "Scenic Thames river catamaran cruise to Greenwich",
      "Traditional English afternoon tea in historic Kensington",
    ],
    itinerary: [
      {
        day: 1,
        title: "Welcome to London",
        description: "Arrive in London, private hotel transfer in Bloomsbury, and evening walk past Covent Garden.",
        activities: ["Hotel check-in", "Covent Garden piazza street performers", "Welcome pub dinner"],
      },
      {
        day: 2,
        title: "Royal Westminster & Guard Ceremony",
        description: "Buckingham Palace gates, St. James's Park, and Westminster Abbey.",
        activities: ["Changing of the Guard ceremony", "Westminster Abbey royal tour", "Big Ben & Parliament views"],
      },
      {
        day: 3,
        title: "Tower of London & Tower Bridge",
        description: "Discover medieval intrigue, the White Tower armory, and the Crown Jewels.",
        activities: ["Tower of London Yeoman Warder tour", "Crown Jewels viewing", "Tower Bridge glass walkway"],
      },
      {
        day: 4,
        title: "Thames Cruise & Maritime Greenwich",
        description: "River cruise past St. Paul's Cathedral down to the Prime Meridian line.",
        activities: ["Thames sightseeing cruise", "Royal Observatory & Meridian Line", "Cutty Sark clipper ship"],
      },
      {
        day: 5,
        title: "British Museum & Kensington Tea",
        description: "Rosetta Stone and Parthenon sculptures followed by tiered scones and clotted cream.",
        activities: ["British Museum guided gallery walk", "Afternoon tea in Kensington garden"],
      },
      {
        day: 6,
        title: "Southbank & West End Theatre",
        description: "Stroll Borough Market food stalls and attend an evening West End musical.",
        activities: ["Borough Market artisanal food tastings", "Tate Modern gallery", "West End theatre show"],
      },
      {
        day: 7,
        title: "Farewell London",
        description: "Morning stroll in Hyde Park before airport departure.",
        activities: ["Hyde Park morning walk", "Airport transfer"],
      },
    ],
    included: [
      "Tower of London and Westminster Abbey fast-track admissions",
      "6 nights central 4-star hotel accommodation with breakfast",
      "Thames river cruise unlimited day pass",
      "Traditional English afternoon tea reservation",
    ],
    excluded: ["International flights", "Theatre ticket upgrades"],
    meetingPoint: "Charing Cross Station Main Entrance, Strand, London",
    cancellationPolicy: "Free cancellation up to 48 hours before tour start for a full refund.",
    languages: ["English"],
    difficulty: "Easy (urban pavements and underground transit)",
    whatToBring: "Comfortable waterproof jacket, umbrella, comfortable walking shoes.",
    featured: false,
    popular: true,
  },
  {
    id: 12,
    slug: "new-york-city-highlights-statue-liberty",
    title: "New York City Highlights & Statue of Liberty Tour",
    description:
      "Feel the legendary pulse of the Big Apple. Cruise out to the Statue of Liberty and Ellis Island Immigration Museum, take in jaw-dropping 360-degree vistas from Summit One Vanderbilt, and wander through Central Park and the High Line elevated park.",
    location: "New York, USA",
    destination: "New York",
    country: "USA",
    category: "City Breaks",
    travelStyles: ["City Breaks", "Cultural"],
    days: 5,
    duration: "5 days / 4 nights",
    groupType: "Small group",
    price: 195.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.7,
    reviews: 478,
    image: featuredTrips[11].image,
    gallery: [featuredTrips[11].image, trendingDestinations[11].image],
    highlights: [
      "Statue of Liberty & Ellis Island ferry and grounds pass",
      "Summit One Vanderbilt skydeck immersion and glass ledges",
      "The High Line elevated garden promenade & Chelsea Market",
      "Central Park guided walking tour from Bethesda Terrace to Strawberry Fields",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival & Midtown Lights",
        description: "Transfer to Midtown hotel, Times Square twilight walk, and Broadway district energy.",
        activities: ["Hotel check-in", "Times Square neon walk", "Classic New York pizza dinner"],
      },
      {
        day: 2,
        title: "Lady Liberty & Financial District",
        description: "Morning ferry to Liberty Island followed by Wall Street and the 9/11 Memorial.",
        activities: ["Statue of Liberty & Ellis Island ferry", "Wall Street & Charging Bull", "9/11 Memorial reflection"],
      },
      {
        day: 3,
        title: "Summit One Vanderbilt & Central Park",
        description: "Mirrored skydecks overlooking the Empire State Building, followed by Central Park paths.",
        activities: ["Summit One Vanderbilt observation deck", "Grand Central Terminal secret whispers", "Central Park Bethesda Fountain"],
      },
      {
        day: 4,
        title: "High Line, Chelsea & SoHo",
        description: "Elevated rail park walking, Chelsea Market bakery tastings, and cast-iron architecture.",
        activities: ["The High Line walking tour", "Chelsea Market lunch", "SoHo boutique shopping walk"],
      },
      {
        day: 5,
        title: "Brooklyn Bridge & Departure",
        description: "Walk the historic wooden boardwalk of Brooklyn Bridge before airport transfer.",
        activities: ["Brooklyn Bridge pedestrian crossing", "DUMBO skyline photos", "Airport departure"],
      },
    ],
    included: [
      "Statue of Liberty & Ellis Island ferry tickets",
      "Summit One Vanderbilt timed entry admission",
      "4 nights boutique hotel in Midtown Manhattan",
      "Expert local native New Yorker guide",
    ],
    excluded: ["International flights", "Dining gratuities"],
    meetingPoint: "Battery Park Castle Clinton Ticket Booth, New York",
    cancellationPolicy: "Free cancellation up to 48 hours before tour start for a full refund.",
    languages: ["English"],
    difficulty: "Moderate (extensive city walking, 10,000+ daily steps)",
    whatToBring: "Comfortable cushioned sneakers, government photo ID, layerable clothing.",
    featured: false,
    popular: true,
  },
  {
    id: 13,
    slug: "sydney-opera-house-bridge-climb",
    title: "Sydney Opera House & Harbour Bridge Climb Tour",
    description:
      "Embrace the sun-drenched outdoor lifestyle of Australia's harbor capital. Take an exclusive architectural tour inside the Sydney Opera House sails, scale the iconic Sydney Harbour Bridge summit, and cruise coastal cliffs from Bondi to Coogee.",
    location: "Sydney, Australia",
    destination: "Sydney",
    country: "Australia",
    category: "Adventure",
    travelStyles: ["Adventure", "Nature", "Beach Escapes"],
    days: 4,
    duration: "4 days / 3 nights",
    groupType: "Small group",
    price: 185.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.8,
    reviews: 256,
    image: featuredTrips[12].image,
    gallery: [featuredTrips[12].image, trendingDestinations[12].image],
    highlights: [
      "Sydney Opera House backstage architectural walking tour",
      "Sydney Harbour Bridge guided summit climb with 360° harbor views",
      "Bondi to Bronte dramatic coastal ocean cliff walk",
      "Manly ferry scenic cruise past Sydney Heads",
    ],
    itinerary: [
      {
        day: 1,
        title: "Harbour Welcome & Circular Quay",
        description: "Arrive in Sydney, check-in to harbor hotel, and stroll through historic The Rocks.",
        activities: ["Hotel check-in", "The Rocks heritage pub tour", "Circular Quay sunset harbor walk"],
      },
      {
        day: 2,
        title: "Opera House & Bridge Climb",
        description: "Official tour of the world-famous sails followed by the bridge summit climb.",
        activities: ["Sydney Opera House interior tour", "BridgeClimb safety & ascent", "Summit celebration photos"],
      },
      {
        day: 3,
        title: "Bondi Coastal Walk & Surf Culture",
        description: "Hike the ocean cliff track from Bondi Beach past Icebergs pool to Bronte.",
        activities: ["Bondi Beach morning stroll", "Coastal trail walk to Bronte", "Fresh seafood lunch overlooking the Pacific"],
      },
      {
        day: 4,
        title: "Manly Ferry & Departure",
        description: "Scenic ferry ride to Manly cove before afternoon departure.",
        activities: ["Manly ferry ocean panorama", "Corso shopping walk", "Airport transfer"],
      },
    ],
    included: [
      "Sydney Opera House official guided tour admission",
      "BridgeClimb Sydney day summit climb with certificate and group photo",
      "3 nights harbor-view hotel accommodation",
      "Ferry passes across Sydney Harbour",
    ],
    excluded: ["International flights", "BridgeClimb personal video packages"],
    meetingPoint: "Circular Quay Wharf 2 Entrance, Sydney",
    cancellationPolicy: "Free cancellation up to 5 days before departure.",
    languages: ["English"],
    difficulty: "Moderate (BridgeClimb requires steady footing on steps)",
    whatToBring: "Comfortable athletic shoes, sunglasses with strap, sunhat, valid photo ID.",
    featured: false,
    popular: true,
  },
  {
    id: 14,
    slug: "istanbul-bosphorus-grand-bazaar",
    title: "Istanbul Bosphorus Cruise & Grand Bazaar Tour",
    description:
      "Straddle two continents where Europe meets Asia across the shimmering Bosphorus strait. Marvel at the soaring minarets of the Blue Mosque, the ancient dome of Hagia Sophia, and the labyrinthine corridors of the Grand Bazaar.",
    location: "Istanbul, Turkey",
    destination: "Istanbul",
    country: "Turkey",
    category: "Cultural",
    travelStyles: ["Cultural", "City Breaks"],
    days: 6,
    duration: "6 days / 5 nights",
    groupType: "Small group",
    price: 155.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.7,
    reviews: 302,
    image: featuredTrips[13].image,
    gallery: [featuredTrips[13].image, trendingDestinations[13].image],
    highlights: [
      "Hagia Sophia & Blue Mosque guided historical tour",
      "Private chartered Bosphorus strait sunset cruise between two continents",
      "Grand Bazaar & Spice Market artisan shopping with local guide",
      "Topkapi Palace imperial treasury and harem apartments",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival in Sultanahmet",
        description: "Transfer to historic Ottoman mansion hotel, and sunset tea overlooking the Marmara Sea.",
        activities: ["Hotel check-in", "Sultanahmet Square orientation", "Turkish meze dinner"],
      },
      {
        day: 2,
        title: "Hagia Sophia & Basilica Cistern",
        description: "Marvel at 6th-century golden mosaics and the subterranean Medusa pillars.",
        activities: ["Hagia Sophia architectural tour", "Basilica Cistern underground walk", "Blue Mosque courtyard visit"],
      },
      {
        day: 3,
        title: "Topkapi Palace & Bosphorus Sunset Cruise",
        description: "Imperial Ottoman suites and private cruise between European and Asian shores.",
        activities: ["Topkapi Palace Harem tour", "Private Bosphorus sunset boat charter", "Fresh fish dinner under Galata Bridge"],
      },
      {
        day: 4,
        title: "Grand Bazaar & Spice Market",
        description: "Navigate centuries-old trading alleys, carpet demonstrations, and Turkish delight tastings.",
        activities: ["Spice Bazaar aromatic tour", "Grand Bazaar leather & carpet masterclass", "Turkish coffee reading"],
      },
      {
        day: 5,
        title: "Galata Tower & Karaköy Art Scene",
        description: "Cross to modern Beyoğlu, ascend Galata Tower, and explore vibrant street art cafes.",
        activities: ["Galata Tower 360° balcony", "Istiklal Avenue historic tram ride", "Farewell Ottoman banquet"],
      },
      {
        day: 6,
        title: "Güle Güle Istanbul",
        description: "Final baklava shopping in Eminönü before airport transfer.",
        activities: ["Hafiz Mustafa confectionery visit", "Istanbul Airport departure"],
      },
    ],
    included: [
      "All historical monument admissions (Hagia Sophia, Topkapi Palace, Cistern)",
      "5 nights historic boutique hotel in Sultanahmet",
      "Private 2-hour chartered Bosphorus boat cruise",
      "Licensed Turkish professional historian guide",
    ],
    excluded: ["International airfare", "Personal carpet purchases"],
    meetingPoint: "Sultanahmet Square Fountain, 34122 Fatih, Istanbul",
    cancellationPolicy: "Free cancellation up to 48 hours before tour start for a full refund.",
    languages: ["English", "Turkish"],
    difficulty: "Moderate (cobblestone walking)",
    whatToBring: "Headscarf for mosque entry, slip-off shoes, cash for bazaar bargaining.",
    featured: false,
    popular: true,
  },
  {
    id: 15,
    slug: "maldives-overwater-bungalow-diving",
    title: "Maldives Overwater Bungalow & Coral Reef Diving",
    description:
      "Escape to paradise on a secluded coral atoll surrounded by warm, crystal-clear turquoise waters. Stay in a luxury overwater bungalow with direct lagoon access, swim with gentle manta rays and sea turtles, and indulge in sunset dhow sailing.",
    location: "Maldives",
    destination: "Maldives",
    country: "Maldives",
    category: "Luxury",
    travelStyles: ["Luxury", "Beach Escapes", "Nature"],
    days: 7,
    duration: "7 days / 6 nights",
    groupType: "Private experience",
    price: 890.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.9,
    reviews: 198,
    image: featuredTrips[14].image,
    gallery: [featuredTrips[14].image, trendingDestinations[14].image],
    highlights: [
      "6 nights in a private luxury overwater villa with plunge pool",
      "Guided marine safari to snorkel with manta rays and whale sharks",
      "Scenic seaplane transfer across North Ari Atoll",
      "Private sandbank candlelit dinner with personal chef",
    ],
    itinerary: [
      {
        day: 1,
        title: "Seaplane Flight & Island Welcome",
        description: "Scenic seaplane flight from Malé to your private island resort.",
        activities: ["Seaplane flight over atolls", "Overwater villa check-in", "Sunset cocktail lounge"],
      },
      {
        day: 2,
        title: "House Reef Exploration",
        description: "Snorkel straight from your villa deck into living coral gardens.",
        activities: ["Guided house reef safari", "Coral restoration workshop", "Lagoon kayak"],
      },
      {
        day: 3,
        title: "Manta Ray & Turtle Marine Safari",
        description: "Boat excursion into Hanifaru Bay biosphere to swim with gentle giants.",
        activities: ["Manta ray research expedition", "Sea turtle sanctuary visit", "Beachfront barbecue"],
      },
      {
        day: 4,
        title: "Private Sandbank Escape",
        description: "Cast away on a completely deserted sandbar for a private chef-prepared picnic.",
        activities: ["Private boat to secluded sandbank", "Gourmet picnic lunch", "Uninhabited reef snorkeling"],
      },
      {
        day: 5,
        title: "Overwater Spa & Sunset Dhow Sail",
        description: "Relaxing Balinese massage over glass-floor treatment rooms and traditional sunset dhow sail.",
        activities: ["Overwater spa treatment", "Traditional Maldivian dhow cruise", "Dolphin pod spotting"],
      },
      {
        day: 6,
        title: "Starlit Dining by the Waves",
        description: "Celebrate your final evening with a candlelit table carved directly into the white sand.",
        activities: ["Stand-up paddleboard in calm lagoon", "Private beach candlelit dinner"],
      },
      {
        day: 7,
        title: "Farewell to Paradise",
        description: "Morning swim before your seaplane flight back to Malé International Airport.",
        activities: ["Final sunrise lagoon dip", "Seaplane transfer to Malé"],
      },
    ],
    included: [
      "6 nights 5-star overwater bungalow with private pool",
      "Roundtrip scenic seaplane transfers from Malé Airport",
      "Full board gourmet dining (breakfast, lunch, dinner)",
      "Daily guided snorkeling excursions with marine biologist",
    ],
    excluded: ["International flights to Malé", "Motorized watersports (jet ski)"],
    meetingPoint: "Velana International Airport (MLE) Seaplane Terminal",
    cancellationPolicy: "Free cancellation up to 14 days before arrival.",
    languages: ["English", "Dhivehi"],
    difficulty: "Easy (pure relaxation with optional swimming)",
    whatToBring: "Swimwear, underwater camera, reef-safe sunscreen, sunglasses.",
    featured: true,
    popular: true,
  },
  {
    id: 16,
    slug: "santorini-sunset-cruise-wine-tasting",
    title: "Santorini Sunset Cruise & Wine Tasting Experience",
    description:
      "Perched high on dramatic volcanic cliffs above the sapphire Aegean Sea. Sail into the submerged caldera aboard a luxury catamaran, swim in natural volcanic hot springs, sample crisp Assyrtiko volcanic wines, and watch the sun melt into Oia's whitewashed skyline.",
    location: "Santorini, Greece",
    destination: "Santorini",
    country: "Greece",
    category: "Beach Escapes",
    travelStyles: ["Beach Escapes", "Cultural", "Food & Wine"],
    days: 5,
    duration: "5 days / 4 nights",
    groupType: "Small group",
    price: 320.0,
    originalPrice: null,
    currency: "USD",
    rating: 4.8,
    reviews: 267,
    image: featuredTrips[15].image,
    gallery: [featuredTrips[15].image, trendingDestinations[15].image],
    highlights: [
      "Caldera catamaran sailing cruise with volcanic hot springs swim",
      "Private wine tour of 3 historic volcanic vineyards with sommelier",
      "Oia cliffside sunset walk and blue-domed church photo session",
      "Akrotiri prehistoric Minoan ruins archaeological tour",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival on the Caldera Edge",
        description: "Transfer to your cliffside cave hotel in Imerovigli overlooking the volcano.",
        activities: ["Hotel check-in", "Caldera rim sunset drink", "Cycladic welcome dinner"],
      },
      {
        day: 2,
        title: "Caldera Catamaran Sailing Cruise",
        description: "Sail from Vlychada marina to the Red Beach, White Beach, and Nea Kameni hot springs.",
        activities: ["Catamaran cruise", "Volcanic hot springs swim", "Onboard Greek barbecue with local wine"],
      },
      {
        day: 3,
        title: "Volcanic Vineyards & Akrotiri Ruins",
        description: "Visit ancient Minoan ruins and sample crisp Assyrtiko and sweet Vinsanto wines.",
        activities: ["Akrotiri archeological excavation walk", "3 winery cellar tastings with cheese pairings", "Pyrgos village walk"],
      },
      {
        day: 4,
        title: "Oia Sunset & Blue Domes",
        description: "Explore the quiet marble alleys of Oia, maritime mansions, and the world-famous sunset.",
        activities: ["Oia photography stroll", "Byzantine castle viewpoint", "Cliffside farewell dinner"],
      },
      {
        day: 5,
        title: "Antio Santorini",
        description: "Morning espresso on your private terrace before airport/ferry transfer.",
        activities: ["Morning Aegean terrace breakfast", "Airport/port departure transfer"],
      },
    ],
    included: [
      "4 nights boutique caldera-view hotel accommodation with breakfast",
      "5-hour luxury catamaran cruise with BBQ dinner and open bar",
      "Winery tour with 12 wine tastings and sommelier guidance",
      "All private airport/port arrival and departure transfers",
    ],
    excluded: ["International flights / ferry tickets", "Greek climate crisis hotel tax"],
    meetingPoint: "Santorini Airport (JTR) or Athinios Ferry Port",
    cancellationPolicy: "Free cancellation up to 5 days before departure.",
    languages: ["English", "Greek"],
    difficulty: "Moderate (caldera cliff steps and cobblestones)",
    whatToBring: "Comfortable flat walking shoes (cobblestones can be slippery), dark swimwear for volcanic hot springs.",
    featured: true,
    popular: true,
  },
];

// Factual operational stats; zero fake review text
export const tourStats = [
  { value: "16", label: "Vetted global destinations" },
  { value: "500+", label: "Handcrafted tour itineraries" },
  { value: "100%", label: "Verified native local guides" },
  { value: "24/7", label: "Human traveler care hotline" },
];

export const travelStyles = [
  {
    title: "Adventure",
    category: "Adventure",
    text: "Active volcano climbs, desert dune safaris, and open horizons.",
    image: trendingDestinations[7].image,
  },
  {
    title: "Beach escapes",
    category: "Beach Escapes",
    text: "Trade busy days for turquoise lagoons, island catamarans, and slow mornings.",
    image: trendingDestinations[14].image,
  },
  {
    title: "Cultural journeys",
    category: "Cultural",
    text: "Meet the living traditions, ancient ruins, and art that make a place unique.",
    image: trendingDestinations[2].image,
  },
  {
    title: "City breaks",
    category: "City Breaks",
    text: "Iconic architecture, world-class gastronomy, and vibrant neighborhood walks.",
    image: trendingDestinations[0].image,
  },
  {
    title: "Luxury experiences",
    category: "Luxury",
    text: "Secluded overwater villas and bespoke private itineraries, impeccably paced.",
    image: trendingDestinations[15].image,
  },
  {
    title: "Nature & wildlife",
    category: "Nature",
    text: "Sacred rainforest terraces, coral reefs, and pristine marine reserves.",
    image: trendingDestinations[12].image,
  },
];

export const benefits = [
  ["Curated itineraries", "Handpicked tours built around real cultural moments, safety, and seamless transit."],
  ["Trusted local guides", "Travel with licensed native specialists who know their destination from the inside."],
  ["Transparent pricing", "Clear inclusions, upfront base rates, and zero surprise booking fees at checkout."],
  ["24/7 human support", "Helpful coordinators are available before, during, and after your trip."],
];

export const faqs = [
  ["How does booking a tour with Viatours work?", "Choose your preferred tour and date, review clear inclusions, and submit your booking request. Our team verifies date availability and sends a confirmation with complete joining instructions."],
  ["What is the cancellation policy on tours?", "Most of our tours offer free cancellation up to 48 hours before departure. Each tour page states its exact policy clearly before you book."],
  ["Can you accommodate custom dates or private groups?", "Yes. If our scheduled departures do not fit your timeline, our coordinators can customize private departures or group bookings of 8+ travelers with dedicated coaches."],
  ["What is included in the published tour price?", "Every tour page lists an itemized breakdown of what is included (accommodations, transport, tickets, guides) and what is excluded."],
  ["Are airport transfers included in tour packages?", "Multi-day tours typically include private arrival and departure transfers from the main international airport or ferry port specified in the itinerary."],
];

export { featuredTrips, trendingDestinations };
